
export const FETCH_PRODUCT_REQUEST = "FETCH_PRODUCT_REQUEST" ;

export const  FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS" ;

export const FETCH_PRODUCT_FAILURE = "FETCH_PRODUCT_FAILURE" ;



export const ADD_TO_CARD = "ADD_TO_CARD" ;

export const REMOVE_FROM_CARD = "REMOVE_FROM_CARD" ;

export const CHECKOUT = "CHECKOUT" ;